# kubernetes/helm/taskflow-app/values.yaml

backend:
  image:
    repository: ghcr.io/mohd2040/taskflow/taskflow-backend
    tag: "20250711-042435"
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 5000
  env:
    # ✅ تم حذف MONGODB_URL و JWT_SECRET من هنا
    # MONGO_URI: "..."
    # JWT_SECRET: "..."
