        # kubernetes/helm/taskflow-app/values.yaml

        backend:
          image:
            repository: ghcr.io/mohd2040/taskflow/taskflow-backend # ✅ تأكد من هذا
            tag: sha-48d7de322933e8eef5476ddd87547bd168783095 # ✅ تأكد من هذا
            pullPolicy: IfNotPresent
          service:
            type: ClusterIP
            port: 5000 # المنفذ الذي يستمع عليه تطبيق Node.js داخل الحاوية
          env:
            MONGO_URI: "mongodb+srv://apiuser:j3HR1ph4HZ7qxK0d@task-manager-api-cluste.p3adibr.mongodb.net/taskmanager?retryWrites=true&w=majority&appName=task-manager-api-Cluster" # ✅ استبدل برابط MongoDB Atlas
            JWT_SECRET: "JWT_SECRET123" # ✅ استبدل بمفتاح JWT السري
        