# kubernetes/helm/taskflow-app/templates/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-backend-deployment
  labels:
    app: taskflow-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskflow-backend
  template:
    metadata:
      labels:
        app: taskflow-backend
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          env:
            # ✅ سحب MONGODB_URL من Secret
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: taskflow-backend-mongo-secret # اسم الـ Secret الذي أنشأناه
                  key: MONGODB_URL # المفتاح داخل الـ Secret
            # ✅ سحب JWT_SECRET من Secret
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: taskflow-backend-jwt-secret # اسم الـ Secret الذي أنشأناه
                  key: JWT_SECRET # المفتاح داخل الـ Secret
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
