# kubernetes/helm/taskflow-app/templates/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-backend-deployment
  labels:
    app: taskflow-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskflow-backend
  template:
    metadata:
      labels:
        app: taskflow-backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.backend.service.port }}
            protocol: TCP
        env:
          - name: MONGO_URI
            value: {{ .Values.backend.env.MONGO_URI | quote }}
          - name: JWT_SECRET
            value: {{ .Values.backend.env.JWT_SECRET | quote }}
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        