# kubernetes/helm/taskflow-app/templates/backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: taskflow-backend-service
  labels:
    app: taskflow-backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
      name: http
  selector:
    app: taskflow-backend