# .github/workflows/destroy-aws-infrastructure.yml

# اسم سير العمل
name: Destroy AWS Infrastructure with Terraform

# ✅ تحديد تشغيل يدوي (Manual Trigger)
# هذا السير لن يعمل تلقائياً عند الدفع، بل يجب تشغيله يدوياً من واجهة GitHub Actions.
on:
  workflow_dispatch:
    # يمكنك إضافة inputs هنا إذا أردت تمرير معلمات معينة عند التشغيل اليدوي
    inputs:
      confirm_destroy:
        description: 'Type "destroy" to confirm deletion of AWS infrastructure'
        required: true
        type: string

permissions:
  contents: read
  id-token: write # مطلوب إذا كنت تستخدم OIDC

jobs:
  terraform-destroy:
    name: Terraform Destroy AWS
    runs-on: ubuntu-latest
    if: false

    # ✅ شرط لتشغيل هذه الوظيفة فقط إذا تم إدخال "destroy" كـ input
    if: github.event.inputs.confirm_destroy == 'destroy'

    steps:
      # 1. Checkout repository: سحب الكود
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. إعداد Terraform: تثبيت Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.x.x # استخدم نفس الإصدار الذي تستخدمه للبناء

      # 3. تهيئة Terraform (terraform init)
      # ضروري للاتصال بالـ backend في S3
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: devops/terraform/aws # مجلد Terraform لـ AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }} # أو secrets.AWS_REGION إذا كان سرًا

      # 4. تخطيط التدمير (terraform plan -destroy)
      # يعرض ما سيتم حذفه. لا يطبق أي تغييرات.
      - name: Terraform Plan Destroy
        id: plan_destroy
        run: terraform plan -destroy -no-color
        working-directory: devops/terraform/aws
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          TF_VAR_aws_region: ${{ vars.AWS_REGION }}
          TF_VAR_ssh_key_name: ${{ secrets.SSH_KEY_NAME }} # تمرير المتغيرات اللازمة للخطة

      # 5. تطبيق التدمير (terraform destroy)
      # ✅ يستخدم '-auto-approve' لتجنب المطالبة بالتأكيد في بيئة CI/CD.
      #    لذلك، التأكيد اليدوي عبر الـ input في بداية السير (confirm_destroy) يصبح حرجًا.
      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: devops/terraform/aws
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          TF_VAR_aws_region: ${{ vars.AWS_REGION }}
          TF_VAR_ssh_key_name: ${{ secrets.SSH_KEY_NAME }}
